### ISSUE TITLE
Is there a sample to get started

### ISSUE THREAD

**Issue by WeihanLi** [rogerfar/Aria2.NET#2]
Hi, thanks for your effort, and I'm new to aria2, is there a sample

**Comment by rogerfar** [comment]
Unfortunately I didn't put much documentation no.

To get started, check out the ApiTest file:
https://github.com/rogerfar/Aria2.NET/blob/master/Aria2NET/Aria2NET.Test/ApiTest.cs

It should cover most methods that are implemented right now.

The methods implemented follow the official API very closely in naming and arguments:
https://aria2.github.io/manual/en/html/aria2c.html#json-rpc-using-http-get

**Comment by WeihanLi** [comment]
Thanks very much
